name: Cross-Compile and Release

on:
  push:

jobs:
  build:
    name: Build for ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: windows
            arch: amd64
            ext: .exe
          - os: linux
            arch: amd64
            ext: ''
          - os: darwin
            arch: amd64
            ext: ''
          - os: darwin
            arch: arm64
            ext: ''
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18 # Update to match your required Go version
    - name: Build
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v -o repo-single-file-export-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: repo-single-file-export-${{ matrix.os }}-${{ matrix.arch }}
        path: repo-single-file-export-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
